# This file contains values from Cookiecutter

default_context:
  project_name: "autostudent"
  project_description: "Description for `autostudent`"
  package_name: "autostudent"
  git_platform: "github"
  username: "WinnerOK"
  git_repo_url: "https://github.com/WinnerOK/autostudent"
  email: "danman339@gmail.com"
  version: "0.1.0"
  python_version: "3.9"
  line_length: "88"
