version: "3.9"

x-application-environment: &app-environment
  TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
  PG_DSN: ${PG_DSN}
  RMQ_DSN: ${RMQ_DSN}
  REDIS_DSN: ${REDIS_DSN}
  MEILI_DSN: ${MEILI_DSN}
  YANDEX_SESSION_ID: ${YANDEX_SESSION_ID}
  GENERATE_SUMMARIZATION_ENDPOINT: ${GENERATE_SUMMARIZATION_ENDPOINT}
  GENERATE_SUMMARIZATION_TIMEOUT_SECONDS: ${GENERATE_SUMMARIZATION_TIMEOUT_SECONDS}
  SUMMARY_POLLING_TIME_MULTIPLIER: ${SUMMARY_POLLING_TIME_MULTIPLIER}

services:
  taskiq-worker:
    image: autostudent:latest
    command: ["taskiq", "worker", "autostudent.broker:broker", "autostudent.tasks"] # по дефолту импортирует к брокеру все tasks.py
    environment: *app-environment
    depends_on: &taskiq-deps
      db-migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      rmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  taskiq-sheduler:
    image: autostudent:latest
    command: ["taskiq", "scheduler", "autostudent.broker:scheduler", "autostudent.tasks"] # по дефолту импортирует к шедулеру все tasks.py
    environment: *app-environment
    depends_on: &taskiq-deps
      db-migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      rmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  meilisearch:
    image: getmeili/meilisearch:v1.7
    volumes:
      - ./shared/meili_data:/meili_data
    environment:
      MEILI_ENV: development # TODO: change in real prod
      MEILI_HTTP_ADDR: "localhost:${MEILI_PORT}"
    ports:
      - "127.0.0.1:7700:${MEILI_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:${MEILI_PORT}/health"]
      interval: 10s
      timeout: 30s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: autostudent:latest
    environment: *app-environment
    depends_on:
      <<: *taskiq-deps
      taskiq-worker:
        condition: service_started
      taskiq-sheduler:
        condition: service_started
      meilisearch:
        condition: service_healthy


  rmq:
    image: rabbitmq:3.13.0-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "127.0.0.1:5672:${RMQ_PORT}"
      - "127.0.0.1:15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q",  "ping"]
      interval: 10s
      timeout: 30s
      retries: 5

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "127.0.0.1:6379:${REDIS_PORT}"
    healthcheck:
      test:  ["CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 5

  db-migration:
    image: autostudent:latest
    command: >
      ./autostudent/entrypoint.sh
    volumes:
      - ./migrations:/app/postgres/migrations:ro
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:10-alpine
    volumes:
      - ./shared/pg_db:/var/lib/postgresql/data
    restart: always
    ports:
      - "127.0.0.1:45432:${PG_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_INITDB_ARGS: '--locale=en_US.UTF-8'
